'use strict';function f(a){return new Promise(function(b,d){var c=new XMLHttpRequest,e=a.url,g=a.type||"GET";c.upload.onprogress=a.progress;c.open(g,e);c.setRequestHeader("X-Requested-With","XMLHttpRequest");a.contentType&&c.setRequestHeader("Content-Type",a.contentType);a.b&&c.setRequestHeader(a.b[0],a.b[1]);c.setRequestHeader("max-age","3600");a.responseType&&(c.responseType=a.responseType);a.data?(e=a.data,FormData.prototype.isPrototypeOf(e)||c.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8"),
c.send(e)):c.send();c.onload=function(){if(200<=c.status&&400>c.status)if(/json/.test(c.getResponseHeader("content-type")))try{var h=c.responseText?JSON.parse(c.responseText):null;b(h)}catch(m){d(m)}else a.responseType?b(c.response):b(c.responseText);else d(c.responseText)};c.onerror=function(h){d(h)}})};function k(a,b){setTimeout(a,100*b)};function l(a){return"string"==typeof a}var n,p;["msT","OT","MozT","webkitT","t"].forEach(function(a){var b=document.body.style,d=a+"ransition";a+="ransform";void 0!==b[d]&&(n=d);void 0!==b[a]&&(p=a)});function q(a){return new r(a)}function r(a){if(!Array.isArray(a)&&a)if(l(a))switch(a=a.trim(),a[0]){case "<":var b=document.createElement("div");b.innerHTML=a;a=b.childNodes;break;default:a=document.querySelectorAll(a)}else a=a.nodeType||a==window?[a]:null;[].push.apply(this,a)}
function t(a,b){[].forEach.call(a,b);return a}function v(a,b,d){return t(a,function(c){b.split(/\s/).forEach(function(e){c.addEventListener(e,d,!1)})})}function w(a,b){return void 0!=b?t(a,function(d){d.innerHTML=b}):a.length?a[0].innerHTML:""}function x(a,b){return l(b)?a.length?(a[0].currentStyle||document.defaultView.getComputedStyle(a[0],""))[b]:"":t(a,function(d){for(var c in b)d.style[c]=b[c]})}
function y(a,b){return l(b)?a.length?a[0].getAttribute(b):"":t(a,function(d){for(var c in b)d.setAttribute(c,b[c])})}function z(a){return q([].filter.call(a,function(b,d){return[].indexOf.call(a,b)==d}))}function A(a){return a.map(function(b){return b.previousSibling})}function B(a,b){return t(a,function(d){d.classList.add(b)})}function D(a,b){for(var d=a.length;d--;)for(var c=a[d],e=c.matches||c.msMatchesSelector;c&&1==c.nodeType;){if(e.call(c,b))return q(c);c=c.parentNode}return!1}
function E(a){return a.map(function(b){return document.importNode(b,!0)})}
r.prototype={get:function(a){return q(this[a])},map:function(a){return q([].map.call(this,a))},text:function(a){return void 0!=a?t(this,function(b){b.textContent=a}):this.length?this[0].textContent:""},offset:function(){return this[0].getBoundingClientRect()},append:function(a){return t(this,function(b){l(a)&&(a=q(a));t(a,function(d){b.appendChild(d)})})},prepend:function(a){return t(this,function(b){l(a)&&(a=q(a));t(a,function(d){b.insertBefore(d,b.firstChild)})})},before:function(a){return t(this,
function(b){l(a)&&(a=q(a));t(a,function(d){b.parentNode.insertBefore(d,b)})})},after:function(a){return t(this,function(b){var d=b.nextSibling;l(a)&&(a=q(a));t(a,function(c){b.parentNode.insertBefore(c,d)})})},remove:function(){return t(this,function(a){a&&a.parentNode&&a.parentNode.removeChild(a)})},parent:function(){return z(this.map(function(a){return a.parentNode}))},next:function(){return this.map(function(a){return a.nextSibling})},find:function(a){var b=q();t(this,function(d){l(d)||((d.matches||
d.msMatchesSelector).call(d,a)?[].push.apply(b,[d]):[].push.apply(b,d.querySelectorAll(a)))});return z(b)},is:function(a){for(var b=this.length;b--;){var d=this[b];if((d.matches||d.msMatchesSelector).call(d,a))return!0}return!1},show:F(0),c:F(1),a:F(3)};
function F(a){return function(b){var d=this;if(2>a)return x(d,{display:0==a?"":"none"});var c;4>a?c=["opacity",1,0]:6>a&&(c=[p,"scale(1)","scale(0)"]);var e={};return new Promise(function(g){t(d,function(h){var m=x(q(h),"display");if(0==a%2&&"none"!=m||1==a%2&&"none"==m)g(d);else{var u=q(h);"none"==m&&(e.display="");var C=h.style[n];b||(b=C?C:".5s");5<a&&(x(u,{visibility:"hidden"}),x(u,e),m=h.offsetHeight,h=h.offsetWidth+h.offsetLeft,e.visibility="",e.overflow="hidden",c=8>a?["left",0,-h+"px"]:["height",
m+"px",0]);e[c[0]]=c[2-a%2];x(u,e);k(function(){e={};e[c[0]]=c[1+a%2];e[n]=b;x(u,e);k(function(){e[c[0]]="";e[n]=C;e.overflow="";1==a%2&&(e.display="none");x(u,e);g(d)},10*parseFloat(b))})}})})}};var G=document.createElement("style");G.appendChild(document.createTextNode("@keyframes ins{0%{opacity:.9}1%{opacity:1}}@-webkit-keyframes ins{0%{opacity:.9}1%{opacity:1}}"));document.head.appendChild(G);var H={};v(q(document),void 0!==document.body.style.animation?"animationend":"webkitAnimationEnd",function(a){if("ins"==a.animationName)H[a.target.tagName](q(a.target))});
function I(a,b){H[a.toUpperCase()]=b;G.appendChild(document.createTextNode(a+"{animation:.1s ins;-webkit-animation:.1s ins}"))};I("tag-button",function(a){var b=a.text();v(a,"click",function(){t(q("nav option"),function(c){c.value==b?c.selected="selected":c.removeAttribute("selected")});var d=document.createEvent("HTMLEvents");d.initEvent("change",!1,!0);q("nav select")[0].dispatchEvent(d);640>window.innerWidth&&window.scrollTo(0,q("nav").offset().top+window.pageYOffset)})});var J=document.implementation.hasFeature("http://www.w3.org/TR/SVG2/feature#GraphicsAttribute","2.0"),K=q("body"),L=q("article");function M(a){var b=a.offset(),d=L.offset(),c=window.innerHeight,e=c-d.top,g=.9*(d.right-b.left);a=d.right-g/9;d=(0<d.top?d.top:0)+.05*e;var h=b.right-g/9,m=b.top;b=b.bottom;c-=.05*e;g=a-g/2;return`M${a},${d}C${g},${d} ${g},${m} ${h},${m}L${h},${b}C${g},${b} ${g},${c} ${a},${c}Z`}
function N(a){a=a.offset();var b=0<a.top?a.top:0,d=window.innerHeight-b;return`M${a.right},${b}c0,0 -${a.width},0 -${a.width},0l0,${d<a.height?d:a.height}c 0,0 ${a.width},0 ${a.width},0Z`}
function O(a,b){var d=q(document.createElementNS("http://www.w3.org/2000/svg","svg"));y(d,{viewBox:`0 0 ${window.innerWidth} ${window.innerHeight}`,id:"genie"});K.append(d);var c=q(document.createElementNS("http://www.w3.org/2000/svg","path"));d.append(c);if(J)y(c,{d:N(b?a:L)}),k(function(){y(x(c,{transition:".5s"}),{d:M(a)})},1),k(function(){y(x(c,{transition:".5s cubic-bezier(.4, 1.6, .5, .8)"}),{d:N(b?L:a)})},5);else{var e=y(q(document.createElementNS("http://www.w3.org/2000/svg","animate")),{attributeName:"d",
repeatCount:"1",dur:"1",calcMode:"spline",keySplines:"0 0 1 1;.4 1.6 .5 .8",keyTimes:"0; .5; 1",fill:"freeze",values:`${N(b?a:L)};${M(a)};${N(b?L:a)}`});c.append(e)}k(function(){d.a().then(function(){d.remove()})},11)};var P;
function Q(a){window.scrollTo(0,0);if(640<=window.innerWidth){x(q("article"),{opacity:0});var b=D(q('nav a[href="'+P+'"]'),"li");b.length?(b.offset().top?O(b):O(q("nav select")),k(function(){x(b,{opacity:1})},11)):O(q("nav select"));var d=D(q('nav a[href="'+a+'"]'),"li");d.length&&d.offset().top?k(function(){O(d,!0)},10):k(function(){O(q("nav select"),!0)},10)}var c=q('nav a[href="'+a+'"]').text();document.title=c.length?c+" | egashira.jp":"egashira.jp";w(q("article"),"<h1>"+c+"</h1>").append(q('<span class="ld"><svg viewBox="0 0 66 66"><circle cx="33" cy="33" r="30"/></svg><span>loading...</span></span>'));k(function(){x(q("article"),
{opacity:1})},21);f({url:a}).then(function(e){e=q(e).find("article");w(q("article"),w(e));e=e.find("script").text();eval(e);R()});P=a}v(q(document),"click",function(a){var b=D(q(a.target),"a");b&&(b=y(b,"href"),/^\/[^\/]+|^\/$/.test(b)&&(a.preventDefault(),b!=location.pathname&&(history.pushState(b,"",b),Q(b))))});v(q(window),"popstate",function(a){a.state&&Q(a.state)});P=location.pathname;history.replaceState(P,"",P);
(w(q("nav")).length?new Promise(function(a){k(function(){a(void 0)},void 0)}):f({url:"/"})).then(function(a){a&&(a=q(a).find("nav"),w(q("nav"),w(a)),a=a.find("script").text(),eval(a));var b=window.tags;640<=window.innerWidth&&(a=q("nav ul"),x(a,{height:window.innerHeight-a.offset().top-5+"px"}));R();var d=q("nav select");Object.keys(b).forEach(function(c){d.append('<option value="'+c+'">'+c)});v(d,"change",function(c){c=c.target.value;var e=q("nav li");if(c){var g=b[c];t(e,function(h,m){h=q(h);0>
g.indexOf(m)?h.c():h.show()})}else e.show()})});
function R(){var a=D(q('nav a[href="'+location.pathname+'"]'),"li");640<=window.innerWidth&&a.length&&x(a,{opacity:.3});var b=q("article");if(a.length){var d=q('<p id="paging">');b.append(d);[a.next(),A(a)].forEach(function(c,e){c[0]&&(c=c.find("a"),c.length&&d.append(B(E(c),"p"+e)));0==e&&d.append('<a href="/">Home</a>')})}b.append('<div id="disq">');a=v(q('<span class="btn icon comment" data-icon="i">Comment</span>'),"click",function(){b.append('<div id="disqus_thread">');if(q("#disqjs").length)window.DISQUS.reset({reload:!0,
f:function(){this.page.identifier=location.pathname.replace("/","_");this.page.url=location.href}});else{var c=document.createElement("script");c.src="//egashira.disqus.com/embed.js";c.id="disqjs";document.body.appendChild(c)}q("#disq").a().then(function(e){e.remove()})});q("#disq").append(a)};I("img",function(a){if(y(a,"data-src")){var b=window.devicePixelRatio||1,d=function(){if(a.offset().bottom){for(var c=a.parent();"inline"==x(c,"display");){if(1!=a[0].nodeType)return;c=c.parent()}c=(c.offset().width-parseInt(x(c,"padding-left"))-parseInt(x(c,"padding-right"))-2*parseInt(x(a,"border-left-width")))*b;var e=parseInt(y(a,"data-width"));var g=parseInt(y(a,"data-height"));e<c?(c=e,e=g):e=Math.floor(c*g/e);g=y(a,"data-src").replace(/https?:/,"")+"=w"+c+"-h"+e;v(y(a,{width:Math.floor(c/b),
height:Math.floor(e/b),src:g}),"error",function(){a.remove()})}else k(d,1)};d()}});
